### ISSUE TITLE
USB instead of serial?

### ISSUE THREAD

**Issue by Aesculapius** [mattsaxon/HASS-Jablotron80#1]
Not sure if this is the right place, but would a connection to the USB port also work? I'm using that to connecct to one specific workstation and would idealy split that use to also connect it to a rpi so homeassistant can use the PIRs... Do you have a tutorial somewhere on how you built it hardware wise?

**Comment by plaksnor** [comment]
These scripts are currently intended to be used with a connection to the USB port. What would you like to build hardware wise? You could just connect your rpi with a printer-USB cable to the alarm system.

**Comment by mattsaxon** [comment]
For the Jablotron 80, there are 3 options for the cables that I'm aware of.

1. Jablotron JA-80T - this is a USB to serial cable that emulates a COM port
2. Jablotron JA-82T - this is a USB to serial cable that is a HID compliant device
3. Build you own

I would have expected any to work, but it should be noted that I'm using option 1 and I don't have specific evidence that other means work yet, in fact I'm looking at a problem with someone using option 2 which is as yet unresolved.

@plaksnor has a JA-10x series device, so he is best able to comment on that.

What control panel do you have?

**Comment by mattsaxon** [comment]
Closed as answered. Yes this code supports USB.
