### ISSUE TITLE
input irq status

### ISSUE THREAD

**Issue by Thoky81** [mattsaxon/HASS-Jablotron80#10]
I tried to move the HA to Intel NUC with Proxmox. HA is running in Ubuntu docker.
When I restart Ubuntu and HA starts loading I am getting these errors. The Jablotron alarm is not connecting in HA. Any idea ? I have search the web but could not find proper answer.

[   73.684771] usb 3-1: input irq status -75 received
[   73.701027] usb 3-1: input irq status -75 received
[   73.717277] usb 3-1: input irq status -75 received
[   73.732579] usb 3-1: input irq status -75 received
[   73.748809] usb 3-1: input irq status -75 received
[   73.765066] usb 3-1: input irq status -75 received
[   73.781314] usb 3-1: input irq status -75 received
[   73.796558] usb 3-1: input irq status -75 received
[   73.812847] usb 3-1: input irq status -75 received
[   73.829107] usb 3-1: input irq status -75 received
[   73.845386] usb 3-1: input irq status -75 received
[   73.860635] usb 3-1: input irq status -75 received
[   73.876889] usb 3-1: input irq status -75 received
[   73.893142] usb 3-1: input irq status -75 received
[   73.909397] usb 3-1: input irq status -75 received
[   73.924699] usb 3-1: input irq status -75 received
[   73.940889] usb 3-1: input irq status -75 received
[   73.957179] usb 3-1: input irq status -75 received
[   73.972452] usb 3-1: input irq status -75 received
[   73.988689] usb 3-1: input irq status -75 received
[   74.004948] usb 3-1: input irq status -75 received
[   74.021214] usb 3-1: input irq status -75 received
[   74.036490] usb 3-1: input irq status -75 received
[   74.052741] usb 3-1: input irq status -75 received
[   74.069034] usb 3-1: input irq status -75 received
[   74.085276] usb 3-1: input irq status -75 received
[   74.100518] usb 3-1: input irq status -75 received
[   74.116773] usb 3-1: input irq status -75 received
[   74.133024] usb 3-1: input irq status -75 received
[   74.149288] usb 3-1: input irq status -75 received
[   74.164716] usb 3-1: input irq status -75 received
[   74.180983] usb 3-1: input irq status -75 received
[   74.197221] usb 3-1: input irq status -75 received
[   74.212459] usb 3-1: input irq status -75 received
[   74.228714] usb 3-1: input irq status -75 received
[   74.244973] usb 3-1: input irq status -75 received
[   74.261387] usb 3-1: input irq status -75 received
[   74.276610] usb 3-1: input irq status -75 received
[   74.292864] usb 3-1: input irq status -75 received
[   74.309084] usb 3-1: input irq status -75 received
[   74.325374] usb 3-1: input irq status -75 received

**Comment by mattsaxon** [comment]
Sorry, no idea, what prompted the change? New firmware, new HA release for example?

**Comment by Thoky81** [comment]
Well I just tried to move to Intel NUC with Proxmox and this happened. The strange thing is that when I disable the Jablotron in HA this input irq status error don’t appear.

**Comment by mattsaxon** [comment]
Please move to https://github.com/tahvane1/jablotron80 as this repo is no longer maintained
