### ISSUE TITLE
0.103.0 update

### ISSUE THREAD

**Issue by Thoky81** [mattsaxon/HASS-Jablotron80#11]
I dont know if is only me but I dont see the alarm in HA after 0.103.0 update.
This is my HA log:

Error while setting up platform jablotron
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/jablotron/alarm_control_panel.py", line 44, in async_setup_platform
    async_add_entities([JablotronAlarm(hass,config)])
TypeError: Can't instantiate abstract class JablotronAlarm with abstract methods supported_features

**Comment by hsk-dk** [comment]
this isue is also seen on https://github.com/plaksnor/HASS-JablotronSystem, a fix will probally work for both

**Comment by mattsaxon** [comment]
I haven’t upgraded to 103 yet, so can’t confirm

**Comment by mattsaxon** [comment]
Here’s a related issue https://github.com/home-assistant/home-assistant/issues/29852

**Comment by Thoky81** [comment]
Thanks, and you are not planing to upgrade HA to see if you can fix it?

**Comment by mattsaxon** [comment]
Fixed in latest version (this commit https://github.com/mattsaxon/HASS-Jablotron80/commit/ff52ddbe2f42eb4ecb8cfdb7f657f03f2680bc38)

**Comment by Thoky81** [comment]
Excellent 👍 Thanks a lot
