### ISSUE TITLE
questions about the installation

### ISSUE THREAD

**Issue by JWTeunisse** [mattsaxon/HASS-Jablotron80#12]
Searching the internet about a ZWave meter-report I stumbled on your HASS-Jablotron80 interface. As I myself have a J80 alarm system installed, I'm curious if your interface also supports the sensor readings like the magnetic door/window and PIR sensors?
- Is the interface cable connected to the central JA-63 'profi' unit or to the control panel itself.
- The central unit has a RJ11plug: can I use this in order to get the requested sensor information from the J80 system?
- Is there a sort of installation manual/document available?
- and is it possible to activate the alarm siren using the interface?

Thanks in advance, best regards, 
Jan Willem Teunisse

**Comment by mattsaxon** [comment]
> Is the interface cable connected to the central JA-63 'profi' unit or to the control panel itself.

Yes... but it's not a JA-60 unit, this works on JA-80 series only, there is also a JA-100 series fork.

> The central unit has a RJ11plug: can I use this in order to get the requested sensor information from the J80 system?

Sensors are not supported in this code, only alarm state (reading and changing). There is much debate on if this works in the JA-100 series fork. In my testing it only worked on JA-80 when in maintenance/service mode, which wasn't a pragmatic solution, so I never added the sensor code.

> Is there a sort of installation manual/document available?

This is all there is I'm afraid https://github.com/mattsaxon/HASS-Jablotron80/blob/master/README.md

There's also a long thread on HA community here https://community.home-assistant.io/t/jablotron-ja-80-series-and-ja-100-series-alarm-integration/113315

> and is it possible to activate the alarm siren using the interface?

Not directly, the way I've achieved this is with an IoT switch connected across one of the physical sensors connections in the control panel. I'm using a Sonoff G1, which runs of 5V (so a USB plug). I have this installed inside the control panel.
