### ISSUE TITLE
0.108.1 update

### ISSUE THREAD

**Issue by Thoky81** [mattsaxon/HASS-Jablotron80#14]
Hi @mattsaxon ,

hope you are doing well these days.

I have recently updated the HA and getting the error in logs with result that the alarm panel is not working. Any idea ?

Log Details (ERROR)
Logger: custom_components.jablotron.alarm_control_panel
Source: custom_components/jablotron/alarm_control_panel.py:158 
First occurred: 12:05:41 AM (2 occurrences) 
Last logged: 12:05:41 AM

The data stream is not recongisable as a JA-82 control panel. Please raise an issue at https://github.com/mattsaxon/HASS-Jablotron80/issues with this packet info [b'\x00\x00\x01\x01']
No packets

Thanks in advance

**Comment by mattsaxon** [comment]
Hi. Im good thanks. Hope you are too.

I haven’t upgraded to 108 yet and on 107.7 where it still works.

What was the last version you were on before upgrade?

I’ll take a look a the release notes and see if there is anything that looks like it may cause this change, but from the log, it looks like the data has changed Coming from the usb serial port, which seems very strange!

**Comment by mattsaxon** [comment]
I just upgraded to 108.2 and the alarm functionality is working fine for me. So
Looks like it is something in your local setup. I’d suggest to check if the serial ports have mapped to the same USB devices as a first step

**Comment by Thoky81** [comment]
Hi, I am sorry but it was like you suggested - the serial port. Thanks
Yeah and btw thanks for asking, I am so far still good and healthy.

Take care

**Comment by mattsaxon** [comment]
Good the hear on both counts
