### ISSUE TITLE
New feature: virtual keypad

### ISSUE THREAD

**Issue by yuripace** [mattsaxon/HASS-Jablotron80#22]
Hi,
its possibile to change the code keypad and made it a virtual keypad (with *, #, ABC, etc..) to control from HA all aspects of the oasis alarm?

**Comment by FraBoCH** [comment]
Hi @yuripace. I'm not sure it's possible as the keypad is actually rendered and managed by HomeAssistant. The jablotron component has not UI per se, it only implements the home assistant alarm interface.
