### ISSUE TITLE
Source alarm name not known yet

### ISSUE THREAD

**Issue by yuripace** [mattsaxon/HASS-Jablotron80#25]
I cannot get the sensor name.
Note that i can see in on the alarm display,even of the alarm Is not armed

Jablotron state change detected: disarmed to arming
Jablotron state change detected: arming to armed_away
Jablotron state change detected: armed_away to triggered
Alarm triggered but source not known yet
jablotron state change detected: armed_away to triggered
Alarm triggered but source not known yet
Jablotron state change detected: armed_away to triggered
Alarm triggered but source not known yet
Jablotron state change detected: armed_away to triggered
Alarm triggered but source not known yet
Jablotron state change detected: armed_away to triggered
Alarm triggered but source not known yet
Jablotron state change detected: armed_away to triggered
Alarm triggered but source not known yet
Jablotron state change detected: armed_away to triggered
Alarm triggered but source not known yet
Unknown status packet is b'\x0e\x00\x00\x00\x00\x00'
Jablotron state change detected: triggered to disarmed
Unknown status packet is b'\xe8\x00\x00\x00\x00\x00'
Unknown status packet is b'\xe8\x00\x00\x00\x00\x00'
Unknown status packet is b'\xe8\x00\x00\x00\x00\x00'

**Comment by FraBoCH** [comment]
Ok @yuripace, let's try to find out the difference between your alarm and mine. That may prove quite tricky, I warn you ;-)

First: 
- what's your precise alarm model number ? I have a JA-82K like @mattsaxon.
- did you configure the sensor names in the configuration.yaml as shown in the readme ? Can you share this configuration ?

Then, the only way to try to figure out why it's not working for you is to log all the packets while you try to trigger your alarm. 
To do that, please replace at line 339:

```
# FOR REVERSE ENGINEERING ONLY: will produce A LOT of logs
 #_LOGGER.debug("Unknown packet %s", packet[1:8])
```
by: 
```
if self.state == STATE_ALARM_TRIGGERED:
   _LOGGER.debug("Unknown packet %s", packet[1:8])
```

This should every unknown packet received when alarm is triggered (and there will be *a lot*). Then post the logged packets here and precise the number of the sensor (in the alarm configuration) which has trigger the alarm. 

On my alarme I get packet "\x07GF\x06\x1f<" when sensor 06 is triggered when armed away, and "\x07EF\x06\x19<" when armed home

**Comment by yuripace** [comment]
THis is my config

alarm_control_panel:
  - platform: jablotron
    serial_port: /dev/hidraw0
    code: 1234
    code_panel_arm_required: false
    code_panel_disarm_required: false
    code_arm_required: true
    code_disarm_required: true
    sensor_names:
      1: "Sensore 1"
      2: "Sensore 2"
      3: "Sensore 3"
      4: "Sensore 4"
      5: "Sensore 5"
      6: "Sensore 6"
      7: "Sensore 7"
      8: "Sensore 8"
      9: "Sensore 9"
      10: "Sensore 10"
      11: "Sensore 11"
      12: "Sensore 12"
      13: "Sensore 13"
      14: "Sensore 14"
      15: "Sensore 15"
      16: "Sensore 16"

automation:
  trigger:
  - entity_id: alarm_control_panel.jablotron_alarm
    platform: state
    to: triggered
  condition: []
  action:
  - data_template:
      message: ALARM! {{ trigger.to_state.attributes.triggered_by }}
    service: notify.notify


the alarm model is the same JA-82K.

this is the log. 
triggered sensor id 8.
 
Jablotron state change detected: armed_home to triggered
  Alarm triggered but source not known yet
 IJablotron state change detected: armed_home to triggered
  Alarm triggered but source not known yet
 IJablotron state change detected: armed_home to triggered
  Alarm triggered but source not known yet
 IJablotron state change detected: armed_home to triggered
  Alarm triggered but source not known yet
 IJablotron state change detected: armed_home to triggered
  Alarm triggered but source not known yet
 IJablotron state change detected: armed_home to triggered
  Alarm triggered but source not known yet
 IJablotron state change detected: armed_home to triggered
  Alarm triggered but source not known yet
 IJablotron state change detected: armed_home to triggered
  Alarm triggered but source not known yet
 IJablotron state change detected: armed_home to triggered
  Alarm triggered but source not known yet
 IJablotron state change detected: armed_home to triggered
  Alarm triggered but source not known yet
  Unknown packet when triggered b'\x07\x06\x08\x19<\x00\x00'
  Unknown packet when triggered b'\x06E\x06\x08\x19<\x00'
 Unknown packet when triggered b'\x032J\xff\x00\x00\x00'
  Unknown packet when triggered b'\x04E\x06\x08\x19\x00\x00'
 Unknown packet when triggered b"\x05<\x00\x00'\xff\x00"
  Unknown packet when triggered b'\x02E\x06\x00\x00\x00\x00'
  Unknown packet when triggered b"\x07\x08\x19<\x00\x00'"
  Unknown packet when triggered b'\x07E\x06\x08\x19<\x00'
  Unknown packet when triggered b"\x02'\xff\x00\x00\x00\x00"
  Unknown packet when triggered b'\x05E\x06\x08\x19<\x00'
  Unknown packet when triggered b"\x04\x00\x00'\xff\x00\x00"
  Unknown packet when triggered b'\x04E\x06\x08\x19\x00\x00'
  Unknown packet when triggered b"\x05<\x00\x00'\xff\x00"
  Unknown packet when triggered b'\x08\x06\x08\x19<\x00\x00'
  Unknown packet when triggered b'\x07E\x06\x08\x19<\x00'
  Unknown packet when triggered b"\x02'\xff\x00\x00\x00\x00"
  Unknown packet when triggered b'\x04E\x06\x08\x19\x00\x00'
  Unknown packet when triggered b'\x05<\x002J\xff\x00'
8  Unknown packet when triggered b'\x03E\x06\x08\x00\x00\x00'
Unknown packet when triggered b"\x06\x19<\x00\x00'\xff"
Unknown packet when triggered b'\x08\x06\x08\x19<\x00\x00'
Unknown packet when triggered b'\x07E\x06\x08\x19<\x00'
Unknown packet when triggered b'\x02w\xff\x00\x00\x00\x00'
Unknown packet when triggered b'\x04E\x06\x08\x19\x00\x00'
Unknown packet when triggered b"\x05<\x00\x00'\xff\x00"
Unknown packet when triggered b'\x08\x06\x08\x19<\x002'
Unknown packet when triggered b'\x07E\x06\x08\x19<\x00'
Unknown packet when triggered b'\x02J\xff\x00\x00\x00\x00'
Unknown packet when triggered b'\x07E\x06\x08\x19<\x00'
Unknown packet when triggered b"\x02'\xff\x00\x00\x00\x00"
Unknown packet when triggered b'\x03E\x06\x08\x00\x00\x00'
Unknown packet when triggered b"\x06\x19<\x00\x00'\xff"
Unknown packet when triggered b'\x08\x06\x08\x19<\x00\x00'
Unknown packet when triggered b'\x07E\x06\x08\x19<\x00'
Unknown packet when triggered b'\x02J\xff\x00\x00\x00\x00'
Unknown packet when triggered b'\x06E\x06\x08\x19<\x00'
Unknown packet when triggered b"\x03\x00'\xff\x00\x00\x00"
Unknown packet when triggered b'\x03E\x06\x08\x00\x00\x00'
Unknown packet when triggered b"\x06\x19<\x00\x00'\xff"
Unknown packet when triggered b'\x02E\x06\x00\x00\x00\x00'
Unknown packet when triggered b"\x07\x08\x19<\x00\x00'"
Unknown packet when triggered b'\x05E\x06\x08\x19<\x00'
Unknown packet when triggered b'\x04\x002J\xff\x00\x00'
Unknown packet when triggered b'\x05E\x06\x08\x19<\x00'
Unknown packet when triggered b'\x04\x002J\xff\x00\x00'
Unknown packet when triggered b'\x03E\x06\x08\x00\x00\x00'
Unknown packet when triggered b"\x06\x19<\x00\x00'\xff"
Unknown packet when triggered b'\x07\x06\x08\x19<\x00\x1e'
Unknown packet when triggered b'\x05E\x06\x08\x19<\x00'
Unknown packet when triggered b'\x04\x00\x1ew\xff\x00\x00'
Unknown packet when triggered b'\x05E\x06\x08\x19<\x00'
Unknown packet when triggered b"\x04\x00\x00'\xff\x00\x00"
Unknown packet when triggered b'\x02E\x06\x00\x00\x00\x00'
Unknown packet when triggered b"\x07\x08\x19<\x00\x00'"
Unknown packet when triggered b'\x07\x06\x08\x19<\x00\x00'
Unknown packet when triggered b'\x05E\x06\x08\x19<\x00'
Unknown packet when triggered b"\x04\x00\x00'\xff\x00\x00"
Unknown packet when triggered b'\x02E\x06\x00\x00\x00\x00'
Unknown packet when triggered b"\x07\x08\x19<\x00\x00'"
Unknown packet when triggered b'\x02E\x06\x00\x00\x00\x00'
Unknown packet when triggered b"\x07\x08\x19<\x00\x00'"
Unknown packet when triggered b'\x07\x06\x08\x19<\x00\x00'
Unknown packet when triggered b'\x05E\x06\x08\x19<\x00'
Unknown packet when triggered b"\x04\x00\x00'\xff\x00\x00"
Unknown packet when triggered b'\x04E\x06\x08\x19\x00\x00'
Unknown packet when triggered b"\x05<\x00\x00'\xff\x00"
Unknown packet when triggered b'\x08\x06\x08\x19<\x00\x00'
Unknown packet when triggered b'\x07\x06\x08\x19<\x002'
Unknown packet when triggered b'\x04E\x06\x08\x19\x00\x00'
Unknown packet when triggered b"\x05<\x00\x00'\xff\x00"
Unknown packet when triggered b'\x02E\x06\x00\x00\x00\x00'
Unknown packet when triggered b"\x07\x08\x19<\x00\x00'"
Unknown packet when triggered b'\x06E\x06\x08\x19<\x00'
Unknown packet when triggered b"\x03\x00'\xff\x00\x00\x00"
Unknown packet when triggered b'\x06E\x06\x08\x19<\x00'
Unknown packet when triggered b'\x03\x1ew\xff\x00\x00\x00'
Unknown packet when triggered b'\x04E\x06\x08\x19\x00\x00'
Unknown packet when triggered b"\x05<\x00\x00'\xff\x00"
Unknown packet when triggered b'\x02E\x06\x00\x00\x00\x00'
Unknown packet when triggered b"\x07\x08\x19<\x00\x00'"
Unknown packet when triggered b'\x07\x06\x08\x19<\x00\x00'
Unknown packet when triggered b'\x06E\x06\x08\x19<\x00'
Unknown packet when triggered b"\x03\x00'\xff\x00\x00\x00"
Unknown packet when triggered b'\x04E\x06\x08\x19\x00\x00'
Unknown packet when triggered b"\x05<\x00\x00'\xff\x00"
Unknown packet when triggered b'\x02E\x06\x00\x00\x00\x00'
Unknown packet when triggered b"\x07\x08\x19<\x00\x00'"
n

**Comment by FraBoCH** [comment]
Hi @yuripace,

That's interesting. It seems you have packet "\x07E\x06\x08\x19<" where I have "\x07EF\x08\x19<". So it looks like you get a "\x06" where I get a "F", but this should be tested with other sensors to be sure. You should also check that you don't receive these packet when not triggered.

What I suggests is to change to "GF" and "EF" to "G\x06" and "E\x06" respectively in the following piece of code:

                    elif (byte_two == 7 and self._triggered_by is None and 
                            (
                                (packet[2:4] == b'GF' and packet[5:7] == b'\x1f<') or # when away
                                (packet[2:4] == b'EF' and packet[5:7] == b'\x19<')  # when home
                            )): 

Let me know of it works for you like that.

**Comment by yuripace** [comment]
hi @FraBoCH 
it works well!!!!

Many thanks!
ps: can i have your help to decipher protocol more? i want be able to get "low battery" sensors message and something more..can you help me? :)

**Comment by FraBoCH** [comment]
I've updated the code to support both my system and yours.

As far as detecting other events, I would also like it, but that's more easily said that done. I've tried a bit to detect the disconnection of a wireless siren, but no luck so far (see issue #21). I suggest to open separate issue for each event to detect for easier tracking. Then, you can help by providing debug logs corresponding to the events to detect.
