### ISSUE TITLE
Support JA-83

### ISSUE THREAD

**Issue by blavak68** [mattsaxon/HASS-Jablotron80#26]
hi 
i am new in homeassistant world ...

i have Jablotron Control Panel JA-83 + serial cable JA-80T
HA 0.18.5 on NAS Synology 220+ in Docker
serial port i see how:
- /dev/serial/by-id/usb-Silicon_Labs_JABLOTRON_serial_interface_1-if00-port0

after installation and startup in HA, control panel will end after a few seconds with GSM error, shortly before GSM error, the message "complete entry" appears on the keyboard screen

can you help with that?

**Comment by mattsaxon** [comment]
Please move to https://github.com/tahvane1/jablotron80 as this is no longer maintained
