### ISSUE TITLE
Jablotron JA-60

### ISSUE THREAD

**Issue by albasee** [mattsaxon/HASS-Jablotron80#28]
Hi mattsaxon
I have the Jablotron JA-60 System. This system can also be controlled over a seria bus. There is an existing software "ComLink". It would be veeery nice, if on could implement the JA-60 system in Home Assistant. Do you think, this should be possible? How can I help you to make this working?. Or what do I have to modify in the JA-80 implementation that this works with the JA-60 system? Thank you very much for your help.

Cheers

Alois

**Comment by mattsaxon** [comment]
Sorry I don't know anything on JA-60 systems, but I'd expect it to be possible. Have you tried using the existing software as it?

It probably wont work, for example, I know the 80 series and 100 series have totally different controls, but the basic software needed is the same.

The approach I'd suggest it to scan the serial ports to see what messages are sent by the ComLink software and then amend the software in this repository to use those codes. There a whole thread devoted to talking about how you do this sort of thing here https://community.home-assistant.io/t/jablotron-ja-80-series-and-ja-100-series-alarm-integration/113315

**Comment by mattsaxon** [comment]
This repo is no longer maintained. If you want to fork something similar, suggest you look at https://github.com/tahvane1/jablotron80
