### ISSUE TITLE
Status of Sensors for Jablotron 80

### ISSUE THREAD

**Issue by Marclinh0** [mattsaxon/HASS-Jablotron80#29]
Hi all
I love this integration but also I'm a little jalous reagrding the people with the Jab100 integration, more specific on the statusof the Binary Sensors
 
I'm new to HA and have a Oasis 80 alarm
In May 2020 Matt wrote that sensor data is not available while the the alarm is in Unset mode.
The O-Link software has a menu where you can read the packets coming from the Control Panel (also in Unset mode)
I have noticed that everytime one of the sensors is  triggered  (I only tested the PIR's) the datastream changes.

Wouln't be possible to use this as part of the programm to identify the status of all sensors , but I mainly interested in Door and Garage sensors
thanks already

**Comment by VimalO** [comment]
I also have a 80-series panel and want to try this but if sensor data is not available it is less interesting.
Has anyone been able to get the sensor statuses for the  80-series?

**Comment by FraBoCH** [comment]
I agree it would be very nice to have sensor exposed to HA with their status, especially in specific use cases like the one I mention in issue #21. 
That's however much easier said that done, but maybe I'll take some time eventually to dive into that. In the meantime, feel free to tinker with the lot of logs when switching to debug and try to figure out the meaning of all those bytes.

**Comment by mattsaxon** [comment]
I took a long time trying to work this out and could only get relevant codes when my system was in maintenance mode, which was not a workable solution, I therefore shelved the feature. It may be possible with other JA80 control panels.

**Comment by ktibor** [comment]
I found this information in the documentation:

Triggered detector indication by text on the keypad display 
31x 
 311 = YES 
 310 = NO 
YES (default)
 
allows the display of open windows & doors,  to view details press '?'

 I'm able to see the status of the sensors (also in unarmed state) with this settings, but sometimes the status remains unchanged till I don't press "?" or I put the system for a while to the armed state.

**Comment by FraBoCH** [comment]
Thanks @ktibor for this information. I'm aware of this setting and I have it activated on my system. Yes, the data should be somewhere in the byte stream we get from the serial interface, but figuring out how it's encoded is yet another story....

**Comment by markunca** [comment]
I am using it through wiring it directly and reading by Arduino. Not best, but only think I figer it out and not having duplicity sensors.

https://github.com/markunca/arduino-jablotron

**Comment by mattsaxon** [comment]
Please move to https://github.com/tahvane1/jablotron80, this has sensor integration
