### ISSUE TITLE
No 'version' key in the manifest

### ISSUE THREAD

**Issue by JohnnyM84** [mattsaxon/HASS-Jablotron80#30]
Getting this error in Homeassistant, is it possible to add it so plugin is still working in the future?
No 'version' key in the manifest file for custom integration 'jablotron'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'jablotron'

**Comment by FraBoCH** [comment]
I fixed it in PR #24. Please make sure you use "Jablotron80" as folder name in custom_components and as platform name for the version to be properly recognized by HA

**Comment by FraBoCH** [comment]
@mattsaxon as HA 2021.6 is out now and prevent custom components without version in the manifest to load, could you please check and merge my PR#24 ?

In the meantime for anyone having the issue, please use content of manifest in https://github.com/FraBoCH/HASS-Jablotron80/blob/master/custom_components/Jablotron80/manifest.json which works with HA 2021.6.

**Comment by mattsaxon** [comment]
Merged, thanks @FraBoCH
