### ISSUE TITLE
support for JA-80BT (bluetooth dongle)

### ISSUE THREAD

**Issue by mazzy89** [mattsaxon/HASS-Jablotron80#31]
Currently I have the Bluetooth dongle. Do you think that it would be supported? At the moment the communication is handled via serial port but I'm not sure if the Home Asisstant OS drivers would find out the Bluetooth as a COM device.

**Comment by mattsaxon** [comment]
Sorry I don't know. As you observe the code works only when it is seen as a COM device. Some drivers support mapping of BT into COM, others do not.

**Comment by mattsaxon** [comment]
Please move to https://github.com/tahvane1/jablotron80, tis has wider support
