### ISSUE TITLE
which alarm_code to use

### ISSUE THREAD

**Issue by lambertvenema** [mattsaxon/HASS-Jablotron80#33]
Hi Matt,

I want to give it a try.

I was wondering which code i should use as the    **code: !secret alarm_code**  ?
should this be the existing code I normally use to arm/disarm my system ?
Or should it be the aministrator code used for configuration of my system ?

Best regards, Lambert

**Comment by FraBoCH** [comment]
Hi Lambert, 

It's any valid existing code you use to normally arm/disarm the system. Personnaly, I've created a new code for this purpose.

Enjoy!
