### ISSUE TITLE
Integration not working

### ISSUE THREAD

**Issue by booroondook-eng** [mattsaxon/HASS-Jablotron80#34]
I use OASIS (Jablotron-80) and JA-80T cable.
My conf is the following:
```
alarm_control_panel:
  - platform: Jablotron80
    serial_port: /dev/ttyUSB0
    code: 8080
    code_panel_arm_required: False
    code_panel_disarm_required: True
    code_arm_required: False
    code_disarm_required: True
    sensor_names: 
      3: "Keyboard"
      4: "Siren"
      5: "Sensor 1"
      6: "Sensor 2"
      7: "Sensor 3"

```
As a result I have in my Home Assistant one new object "alarm_control_panel.jablotron_alarm" which is always in "unavailable" state. And that is all. I tried to arm and disarm my Jablotron. I also created alarms by moving my hand near the sensors. The alarm worked and the siren sounded, but no events were recorded in the Home Assistant.

**Comment by mattsaxon** [comment]
Fixed in latest code version
