### ISSUE TITLE
Can i see the trigger a bit earlier ?

### ISSUE THREAD

**Issue by lambertvenema** [mattsaxon/HASS-Jablotron80#35]
I got the integration working ::)).
Well that means  i have the controle panel in Home assistant now.
And i can arm and disarm the system corectly.

When i arm the system and come home later ther is a waiting time before the alarm goes in a loud Sirene of 120db.
I hoped to see the trigger  before this waiting time is gone because i do not want that loud sirene to hear everytime i want to check  wether my system still works/triggers correctly on all devices.

Can i already see the trigger on that early moment (during the waiting time in which i can disarm the system) ?
Maybe using a slightly different automation ?

Many Thanks, Lambert

**Comment by mattsaxon** [comment]
Please move the maintained repo at https://github.com/tahvane1/jablotron80. This is a much better integration.,
