### ISSUE TITLE
Alarm code

### ISSUE THREAD

**Issue by Thoky81** [mattsaxon/HASS-Jablotron80#5]
Is there a possibility to skip (exclude) the (alarm) code line in configuration or something in order to always use the keypad on alarm control panel in HA? Right now I am arming/arming home/disarming without the code entered in HA alarm card - just the buttons.

**Comment by mattsaxon** [comment]
So you want to enter the code for both setting and unsetting? Does you physical alarm panel also require this or do you want the HA alarm panel to have different behaviour?

**Comment by Thoky81** [comment]
Yes I would like to have this option to enter the code. My physical alarm also require this if using the keypad but not with the remotes.

**Comment by mattsaxon** [comment]
Added in this [commit](https://github.com/mattsaxon/HASS-Jablotron80/commit/386814b3f143ca8c5405035ee514fb3acded9120)

**Comment by mattsaxon** [comment]
@Thoky81 have you been able to test to verify this works as expected?

**Comment by Thoky81** [comment]
Yes, its working. Thanks for great job.
