### ISSUE TITLE
USB over IP

### ISSUE THREAD

**Issue by Thoky81** [mattsaxon/HASS-Jablotron80#8]
For those who are struggling with setup sharing the USB over the ethernet like I was 😀, please follow this link: https://derushadigital.com/other%20projects/2019/02/19/RPi-USBIP-ZWave.html 
I can confirm the Jablotron Alarm its working between RPi as a server and Ubuntu in VM as a client with installed Hassio on docker.
At the the end in client side just use ..

$ dmesg | grep usb
$ dmesg | grep hid

.. to find out the correct device name.

Good luck

**Comment by mattsaxon** [comment]
Updated readme with information on USB to IP.
